export {default as Dashbord} from './pages/Dashbord'
export {default as Collection} from './pages/Collections'
export {default as Programs} from './pages/Programs'
export {default as AdminDashboard} from './pages/AdminDashboard'
export {default as Detail} from './pages/pembayaran'
export {default as Login} from './pages/Auth/Login'
export {default as Register} from './pages/Auth/Register'
